name: CI

on:
  pull_request:
    branches: [main, silva, dbaltaza]
  push:
    branches: [main, silva, dbaltaza]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mazegenerator-2.1.0-py3-none-any.whl

      - name: Lint
        run: |
          flake8 .
          mypy . --warn-return-any --warn-unused-ignores \
            --ignore-missing-imports --disallow-untyped-defs \
            --check-untyped-defs

      - name: Tests
        run: pytest -q